### ISSUE TITLE
Configuration Builders requesting List access to Key Vault after upgrading from 2.0.0 beta to 2.0.0 RC

### ISSUE THREAD

**Issue by Bmartin2013** [aspnet/MicrosoftConfigurationBuilders#109]
In our .NET Framework project we were using the Configuration Builders 2.0.0 beta and we were getting Key Vault access through a Service Principal, which had only Get permissions in the Key Vault.

When upgraded NuGets to 2.0.0 RC, Configuration Builders started to ask for List permissions in the Key Vault.

```
RequestFailedException: 
Status: 403 (Forbidden)

Content:
{"error":{"code":"Forbidden","message":"Operation is not allowed.\r\nOperation: \"list\"\r\nCaller: appid={appId};oid={oid};numgroups=0;iss=https://sts.windows.net/{tenantId}/\r\nVault: {vault};location={location}","innererror":{"code":"ForbiddenByPolicy"}}}
```

What changed between 2.0.0 beta and 2.0.0 RC that now List permission is mandatory? Is this the expected behavior?

**Comment by StephenMolloy** [comment]
The Azure SDK team asked us to move to the newer supported SDK for KeyVault, and that happened between beta and RC. But I'm not able to reproduce your error without enabling secret name preloading in RC, which should always have required the List permission since listing all secrets in the vault is exactly what that feature does. You can disable preloading by setting `preloadSecretNames="false"` on your builder if you don't want to grant List permissions.
