### ISSUE TITLE
Do any of these packages work in .NET Core?

### ISSUE THREAD

**Issue by madelson** [aspnet/MicrosoftConfigurationBuilders#113]
The underlying ConfigurationBuilder infrastructure seems to come from Microsoft.Extensions.Configuration which supports .NET Core (at least the NuGet package does). However, these packages don't have explicit targets for .NET Standard or .NET Core.

**Comment by StephenMolloy** [comment]
Nope. There is no association with Microsoft.Extensions.Configuration at all. The whole idea behind System.Configuration.ConfigurationBuilders and this suite of key/value config builder implementations was to attempt to provide a veil of modernity that resembles the .Net Core config paradigm in the old .Net desktop world. These packages are strictly intended for netfx* only, though there are frequently .Net Core-targeted equivalents for most of the config sources we provide here.

**Comment by madelson** [comment]
Thanks @StephenMolloy. Just so I understand, does reading in a app.config file using ConfigurationManager not work on .NET Core at all? 

If it does work, is there a similar capability to have ConfigurationManager include information from non-config-file sources like environment variables?

For context, the reason I'm interested in this is that we have a large number of internal libraries that leverage ConfigurationManager to allow their host applications to customize behavior. We'd like for these libraries (which today are .NET Framework only) to support both .NET Framework and .NET Core. Since ConfigurationManager seems to live in both worlds, we were hoping that ConfigurationBuilders and the associated infrastructure would as well.

**Comment by StephenMolloy** [comment]
Ahh, I see. To be honest, I don't know much about ConfigurationManager in .Net Core. I believe it was ported from .Net 4.7, and the underlying config processing architecture it brings does not include ConfigurationBuilders which were introduced in 4.7.1. I don't know if the .Net Core team has any plan to update ConfigurationManager along those lines since config builders are a band aid for the old config system to get information that is easily obtained other ways in .Net Core.  (I believe the .Net Core ConfigurationManager lives in this repo if you want to take a look - https://github.com/dotnet/corefx/tree/master/src/System.Configuration.ConfigurationManager/src/System/Configuration)
