### ISSUE TITLE
Azure.Identity.ClientCertificateCredential Authentication to AzureKeyVault

### ISSUE THREAD

**Issue by D4ve0s** [aspnet/MicrosoftConfigurationBuilders#125]
I am currently using a connection string to connect an on-premise IIS web farm [ASP.NET] to Azure KeyVault using client certificate authentication. I am unable to update this package since V2 has switch to Azure.Identity and DefaultAzureCredential. I need configuration support added so ClientCertificateCredential can be used. Are there any plans to add this support?

**Comment by mikewop** [comment]
I would vote for this feature as well.

We ended up implementing a custom AzureKeyVaultConfigBuilder based in the code here that supports ClientCertificateCredential and DefaultAzureCredential

**Comment by StephenMolloy** [comment]
Fixed with #174 and #142.

The former updates to use Azure.Identity 1.2 which adds `EnvironmentCredential` to the list of possible credential sources in the default credential we use. This can be used for assigning user-managed and client-cert based credentials. (Note, individual projects can always update the Azure.Identity package on their own to get these new capabilities without waiting for this project to update dependency requirements. And in fact this may be desirable as it is a goal of this project to _not_ force dependency updates on anyone using us without a really good reason. In this case we went up to Azure.Identity 1.2, but did not go as far as 1.4 which adds support for logging in with Azure PS through the default credential.)

For projects that need capabilities beyond what DefaultAzureCredential can provide, #142 offers the ability to provide your own credentials by sub-classing either of our Azure builders.

I believe either approach should work for this issue and allow updating to the more current builders when they release. (Or the 2.0 builders and just manually update the Azure.Identity version yourself in your project.)
