### ISSUE TITLE
Multiple keyvault url support

### ISSUE THREAD

**Issue by vishnuvgdemos** [aspnet/MicrosoftConfigurationBuilders#131]
Is there a way to provide multiple keyvault url (Primary & Secondary) so that if one fails, it fallback to next without any exception. I think no.

I tried to give an alternative way through this code but that raise an exception. 
 ```
<builders>
        <add name="AzureKeyVault1" uri="https://mykevault1.vault.azure.net"  type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
        <add name="AzureKeyVault2" uri="https://mykevault2.vault.azure.net"
             type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
        </builders>

 <connectionStrings configBuilders="AzureKeyVault1,AzureKeyVault2">
    <add name="CloudConnectionString" connectionString="my blob" />
  </connectionStrings>
```

Any suggestions to provide multiple keyvault urls?

**Comment by StephenMolloy** [comment]
No, not directly in the way you are hoping for. The goal of these config builders is to keep things simple while maintaining reasonable flexibility, and adding fallback options like you described would add more complexity to the messy and restricted declarative construct we are working with in configuration/xml.

However, you could declare the config builders in your example with the `optional="true"` tag to prevent them from throwing an exception if they fail to connect to AKV - and also use `mode="Expand"` for each of them. Then in your `<connectionStrings>` section you would set the connectionString _value_ to "${CloudConnectionString}" or whatever the key for your connection string in your key vault is. Then the first builder 'AzureKeyVault1' would get the first crack at replacing that token with a real value. If it is able to do so, then it does and the second builder won't ever see the original token. If AKV1 is _not_ able to replace the token though, then AKV2 will get it's chance.

This is not an ideal fallback mechanism. It requires using "Expand" mode instead of one of the other modes, and it also "executes" the second config builder every time instead of only as a fallback. But this approach should functionally achieve what you need.

Alternatively, we have not sealed the base or any builders in this project, so they can easily be extended on a project by project basis.
