### ISSUE TITLE
Works in Visual Studio 19, but not when deployed into Docker Container.

### ISSUE THREAD

**Issue by ghost** [aspnet/MicrosoftConfigurationBuilders#141]
Works fine in development on Windows 10, using Visual Studio 2019, 

However when deployed in to a Windows Server Core 2019 Image, using Docker, it simple doesn't work at all.

Are there undocumented dependencies?

`  <configSections>
    <section name="configBuilders" type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" restartOnExternalChanges="true" requirePermission="false" />
  </configSections>`

`  <configBuilders>
    <builders>
      <add name="Environment" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
    </builders>
  </configBuilders>`

 I omitted the actual connection strings...

` <connectionStrings configBuilders="Environment">`

**Comment by StephenMolloy** [comment]
A simple test would be to set your config builder to 'Greedy' mode and see what environment variables it pulls in. What you have shown in your sample configuration looks good to me, provided there is actually a match between a connection string name in your config and an environment variable name for your process. The 'Greedy' trick would be a quick way to find a disconnect there.

But I suspect you might not have the environment variables set in your docker container that you think you do? Are you running a standalone executable, or are you running an ASP.Net/IIS-based app in your container?

**Comment by ChocoMachine** [comment]
> A simple test would be to set your config builder to 'Greedy' mode and see what environment variables it pulls in. What you have shown in your sample configuration looks good to me, provided there is actually a match between a connection string name in your config and an environment variable name for your process. The 'Greedy' trick would be a quick way to find a disconnect there.
> 
> But I suspect you might not have the environment variables set in your docker container that you think you do? Are you running a standalone executable, or are you running an ASP.Net/IIS-based app in your container?

I updated to config to Greedy as suggested and re-tested.

The Environment Variable Name is good and matches the connection string name. It's the same as on the Dev' machine. (  logconnOdbc ). I have added logging so I can see the actual connecting string being returned from ConfigurationManager and it's the same string that is the placeholder e.g. Web.Config **... connectionString="placeholder here"** whereas if I run on my Dev' machine the transformation  takes place.

I have even added **(Get-IISAppPool "dashboardApi").Recycle()**; to restart the appPool, to force a re-read of the environment variables.

If I run **Get-ChildItem env: | Sort-Object Name** in the container the Environment Variable is there OK. 

I'm stuck, which is why I thought it would be dependencies, but if that was the case I would have expected a run time error.

I'm using mcr.microsoft.com/windows/servercore:ltsc2019 image.

If there was an issue with the installed  .NET version then I would have assumed an error.

I noticed some of the dependencies used .NET Core, would .NET Core need to be installed?

I'm guessing...

**Comment by StephenMolloy** [comment]
I notice that you're not using an ASP.Net or IIS container, which is probably why you don't see environment variables in ASP.Net.

Windows containers have the annoying habit of only setting environment variables for the entry process. Since IIS is a service, it does not get any of these variables that get set. Both the [IIS](https://github.com/microsoft/iis-docker/blob/main/windowsservercore-ltsc2019/Dockerfile) and [ASP.Net](https://github.com/microsoft/dotnet-framework-docker/blob/main/src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile) containers take steps to make these variables visible to web applications via a tool called 'ServiceMonitor.exe'. I believe this also needs to be your entry point or else it won't be able to see environment variables either, and thus won't be able to inject them into IIS.
