### ISSUE TITLE
User assigned managed identities is not supported for Azure Key Vault

### ISSUE THREAD

**Issue by anktsrkr** [aspnet/MicrosoftConfigurationBuilders#154]
Issue - 
AzureKeyVaultConfigBuilder does not support User assigned managed identity.

https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/Azure/AzureKeyVaultConfigBuilder.cs#L93

Fix - 
As per [documentation](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme#specifying-a-user-assigned-managed-identity-with-the-defaultazurecredential), we need to pass **userAssignedClientId** which is missing.

As a fix, I guess we need to add a element to accept userAssignedClientId from users, and based on the value it will be something like this - 

```
var userAssignedClientId =  UpdateConfigSettingWithAppSettings(userAssignedClientIdTag);

var credential = string.IsNullorEmpty(userAssignedClientId)?new DefaultAzureCredential(): new DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = userAssignedClientId });

 _kvClient = new SecretClient(new Uri(_uri), credential );  
```

It seems the same issue exists in AzureAppConfigutaionBuilder as well -

https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/AzureAppConfig/AzureAppConfigurationBuilder.cs#L100

**Comment by StephenMolloy** [comment]
Fixed with #174 and #142.

The former updates to use Azure.Identity 1.2 which adds `EnvironmentCredential` to the list of possible credential sources in the default credential we use. This can be used for assigning user-managed and client-cert based credentials. (Note, individual projects can always update the Azure.Identity package on their own to get these new capabilities without waiting for this project to update dependency requirements. And in fact this may be desirable as it is a goal of this project to _not_ force dependency updates on anyone using us without a really good reason. In this case we went up to Azure.Identity 1.2, but did not go as far as 1.4 which adds support for logging in with Azure PS through the default credential.)

For projects that need capabilities beyond what DefaultAzureCredential can provide, #142 offers the ability to provide your own credentials by sub-classing either of our Azure builders.
