### ISSUE TITLE
How I can map direct from json to section?

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [aspnet/MicrosoftConfigurationBuilders#162]
Hey! How I can map directly from json to ConfigurationSection? Most likely how you did with connectionStrings, but only on root element.

Example 
JSON file:
```JSON
{
  "ApiConfiguration ": {
    "Setting1": "aaaa",
    "Setting2": "bbbb"
  },
}
```
Section ApiConfiguration  class nested from ConfigurationSection
```XML
<ApiConfiguration configBuilders="appSettingsJson" />
```
must got as result something like xml 
```XML
<ApiConfiguration Setting1="aaaa" Setting2="bbbb" />
```

**Comment by dmitriy-pisarevskiy** [comment]
looks like I found something SectionHandler<T>

**Comment by StephenMolloy** [comment]
Yes, `SectionHandler<T>` is the way to handle this scenario. Traditionally, a section handler would iterate over the child nodes of its given section rather than the attributes of the section node... but that's a choice made by the section handler. If your 'ApiConfiguration' section expects settings as attributes, then this is the correct way to do it.
