### ISSUE TITLE
configBuilders attribute on connectionStrings element and Settings.settings

### ISSUE THREAD

**Issue by dannydombrowski** [aspnet/MicrosoftConfigurationBuilders#39]
VS version : 15.9.2

Let me start by saying this is a great package! Thank you for the time / effort.

In asp.net when using the attribute configBuilders on the connectionStrings element, the Settings.settings file, generated by Visual Studio for the ApplicationSettings, will cause an XML error when trying to open the GUI to edit the file.

![image](https://user-images.githubusercontent.com/23314895/49166160-c8d8c880-f300-11e8-8518-2acdc565e5c2.png)

```xml  
 <configBuilders>
    <builders>
      <add name="Environment" mode="Strict" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=1.0.0.0, Culture=neutral" />
    </builders>
</configBuilders>

 <connectionStrings configBuilders="Environment">
      <add name="FakeProject1337.Properties.Settings.ServiceBusUrl" connectionString="secret" /> 
 </connectionStrings>
```

If this is a known issue, I apologize for the duplicate.

Currently this make this great solution to dockerizing our applications impossible to use. 
Any help with this issue would be greatly appreciated.

**Comment by dannydombrowski** [comment]
So, after searching for hours, posting an issue, I thought of a dirty fix.

Since `settings.settings` has problem with the attribute, let's only add the attribute at build time using the config transformers.

So in my .csproj, I'm adding a BeforeBuild step :
```xml
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets" />
  <Target Name="BeforeBuild">
    <TransformXml Source="Web.config" Transform="Web.ConfigBuilder.config" Destination="Web.config" />
  </Target>
```

and this build step reference a file I added in my project named `Web.ConfigBuilder.config`
with the following content :

```xml
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <connectionStrings configBuilders="ConnectionStringsEnvironment" xdt:Transform="SetAttributes"/>
</configuration>
```

This fix my current problem, but I still consider it at a hack and not a proper fix.

**Comment by StephenMolloy** [comment]
This is an unfortunate known issue with configuration builders in general. What is happening here is Visual Studio is trying to load your config file, and when it gets to the config builder part, it can't load the config builder because the dll for the builder is not in Visual Studio's path.

If you want a dirty workaround for just your machine that doesn't involve ugly msbuild config tranformations, you could drop your config builder dll's into a directory that Visual Studio looks in. Or in the GAC.

Other than that, there's not much we can do about it in this repo as the error happens before we ever see the light of day.
