### ISSUE TITLE
SectionHandler<T> doesn't appear to be exposed

### ISSUE THREAD

**Issue by recurs10n** [aspnet/MicrosoftConfigurationBuilders#52]
The readme.md file states that it should be possible to create new section handlers by implementing the SectionHandler<T> class, but that class doesn't appear to be exposed by any of the nuget packages. I've installed the Base package as the readme instructs, but I've also installed all the other packages as well just to be sure. Am I looking in the wrong place for it?

**Comment by StephenMolloy** [comment]
It's a 2.0 feature... and 2.0 is still in beta/preview.
https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/master/src/Base/SectionHandler.cs#L20

I believe there is an issue with loading section handlers from an assembly other than the Base.dll anyway. So that will need to be addressed in the next refresh of the 2.0 preview.
