### ISSUE TITLE
replacement values are not escaped, double quote in password can lead to syntax error

### ISSUE THREAD

**Issue by hn3000** [aspnet/MicrosoftConfigurationBuilders#55]
We used config builders to pull configuration values from environment variables for an IIS hosted Web Project.

When configuration values contain unescaped double quotes, syntax errors result, probably caused by the way that KeyValueConfigBuilder inserts the values into the raw xml -- the person inserting the values into the environment did not expect XML escaping rules to apply.

Steps to reproduce:
- use ${environment:DB_URL} as connection string
- set DB_URL to a value containing `Password="`

Result: application won't start.
Expected: necessary escaping is applied to value pulled from environment

This behaviour is probably not restricted to the EnvironmentConfigBuilder .

Even if the behavior is intentional, an option to have XML escaping handled for us would be very welcome, the current behaviour should at least be documented more thoroughly.

**Comment by StephenMolloy** [comment]
For simply pulling whole connection strings from the environment, I would recommend using your config builder in 'Strict' mode if possible, or exploring 'Greedy' mode with some prefix handling. Both of these modes work with configuration objects instead of raw xml strings, and thus they aren't vulnerable to this escaping issue.

For 'Expand' mode, I think this suggestion makes sense. I'll see if I can do something about this in V2.

**Comment by StephenMolloy** [comment]
#64
