### ISSUE TITLE
NuGet package is out of date

### ISSUE THREAD

**Issue by alasdaircs** [aspnet/MicrosoftConfigurationBuilders#81]
I want to use the AzureAppConfigurationBuilder in a .NET 4.7.2 legacy project, and in particular I want to use the substitution of variables into the labelFilter which arrived in `58_AzConfig-More-AppSettings-Params` (690785b5b6771a570411de663d0c98e04024bc7c). This change happened after the latest (and only) publicly available [NuGet package](https://www.nuget.org/packages/Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration/1.0.0-beta) was built, probably from the `2.0-Beta`(5a06cd87464c2a96fc1e9bf5560f1d7cc327763c) label. The [documentation](../blob/master/README.md) now describes behaviour which isn’t present in any available NuGet package. I have tried compiling from source, but the code has dependencies on `Microsoft.Azure.AppConfiguration.AzconfigClient.dll` and `Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.dll`, neither of which are available on Github. I tried removing the strong-naming and simply referencing those DLLs directly, but I was then stumped by a CS0281 compile-time error `Friend access was granted to 'Microsoft.Azure.AppConfiguration.AzconfigClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=69dad7634abb75e4’, but the public key of the output assembly (‘’) does not match that specified by the InternalsVisibleTo attribute in the granting assembly`. So, unless I get down & dirty with an IL editor or decompiler, I can’t built this project.

Summary
- The NuGet is out of date and does not fully implement the description in the documentation.
- There are no publicly visible nightly builds.
- The code can’t be built outside Microsoft, even after removing the code signing.

Is this the place to ask:
- for a new NuGet package to be published?
- for the dependencies to be open-sourced on Github, or at least published as separate NuGet packages without funky friend attributes to make it possible to build the project from source?

**Comment by StephenMolloy** [comment]
I just closed #75 yesterday, sort of addressing this issue. But let me address your points directly.

I expect to get a refresh of the 2.0 builders out to nuget this month. These would be "rtm" packages for everything except the AzureAppConfigurationBuilder, which would be another "beta2" or "rc." The reason for that is the SDK that is used for interacting with the AppConfiguration service is still in preview. There are no nightly builds because this is a small and infrequently visited project, and it's really just me working on it.

In general, this project should be able to build in a regular old VS environment, not requiring any special Microsoft tools or access. (Code signing being the exception, but that should only "light up" in our build pipeline, and not cause build failures out of the box for folks who clone this repo.) So usually, if there is a new feature or concept checked into a branch, but not released on nuget yet, folks should still be able to build their own from the repo. But if you find build problems in the project, by all means, let us know. We won't be able to support all environments of course, but this repo certainly isn't meant to only be buildable within Microsoft.

Your specific build error here is because the AzconfigClient package is/was an internal and temporary means to access the AppConfig service when we started building support libraries for the service internally. There were plans for, but no actual implementation of an official SDK for interacting with the AppConfig service at the time. The refresh package I'm trying to get out by the end of this month will have migrated to the official SDK for App Configuration which is currently in preview on nuget now.
