### ISSUE TITLE
Is there any ETA for v2?

### ISSUE THREAD

**Issue by pbiasotti** [aspnet/MicrosoftConfigurationBuilders#84]
I'm not sure if this is the correct place to ask this. 

Just wondering when is v2 targeted to be a stable release. We would like to use [Section Handlers](https://github.com/aspnet/MicrosoftConfigurationBuilders#section-handlers) for some custom sections we are using in our prod environments but using a beta version do not give us much confidence on stability.

**Comment by chriswill** [comment]
There are bugs in the current Nuget package that are fixed in the current code base.  At the very least, if you aren't ready to go to production yet, can you please update the Nuget package?  The current version was posted 10 months ago yet there have been a number of commits since that time.

FYI, the bug is about reading a json file in sectional mode.  Retrieving ConnectionStrings by name works in web apps but fails in .Net Console apps, using the same file.

**Comment by StephenMolloy** [comment]
2.0 RC is up here in the repo now. I don't have nuget upload permissions. So soon after the folks with the correct permissions for uploading to ASP.Net's nuget return from the holiday break, I'll get packages on nuget.org.

RTM for the builders that existed in V1 should follow after a couple weeks of comment period. I don't anticipate there will be any changes from RC, but I want to give people a chance to dig in a bit and report any final issues before declaring RTM.

RTM for AzureAppConfigurationBuilder will only happen after:
  1) This repo generally declares 2.0 RTM
  2) The Azure AppConfiguration service officially GA's (sometime in January - https://github.com/Azure/AppConfiguration-Announcements/issues/2)
  3) The SDK for accessing the Azure AppConfiguration service upon which this builder depends also declares RTM.
