### ISSUE TITLE
AzureKeyVaultConfigBuilder crashes when it can't connect.

### ISSUE THREAD

**Issue by martingbrown** [aspnet/MicrosoftConfigurationBuilders#93]
Maybe this is deliberate and I'm using it wrong? However I was trying to create a web.config file that would work both on my development machine and in production. My theory was that I would be able to add configuration for both an AzureKeyVaultConfigBuilder and UserSecretsConfigBuilder and which ever one found its config would win. There is no UserSecrets file in production and there the KeyVault is not accessable from my local machine.

I configured my builders like this:

```
<configBuilders>
    <builders>
      <add name="AzureKeyVault" type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure" vaultName="{redacted name}" />
      <add name="UserSecrets" type="Microsoft.Configuration.ConfigurationBuilders.UserSecretsConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.UserSecrets" userSecretsFile="~\App_Data\Secrets.xml" />
    </builders>
  </configBuilders>
```

Then I declared the appSetting section like this:
```
<appSettings configBuilders="UserSecrets,AzureKeyVault">
```

However when I run the code locally I get the following error.

````
Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{RedactedGUID}. Exception Message: Tried the following 4 methods to get an access token, but none of them worked.
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{RedactedGUID}. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{RedactedGUID}. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. 
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/{RedactedGUID}. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,
operable program or batch file.
````

That is suggesting that it can't connect to the KeyVault which is correct, it can't because my local machine isn't in Azure.

I was assuming that I would only get an error if the config settings couldn't be found in any of the config builders. Does this mean that I'm going to have to start using separate config files for both environments? If so that rather defeats the whole benefit of configuration builders from my point of view.

**Comment by StephenMolloy** [comment]
When this set of config builders was first released, we had considered for each builder whether or not it was reasonable for developers to declare builders that would essentially be no-ops because the underlying config source didn't exist in certain environments. The idea being that if somebody configured a builder to be used - and that builder essentially ended up not executing - should we make noise about that or not?

The default had to be 'yes'. We can't simply silently ignore a failure to retrieve config information (even if that set of config values is empty) that is implicitly asked for by tagging sections in config with a builder. Conversely, we could see valid cases for developers wanting to ignore such failures to retrieve config values. Specifically, the UserSecrets scenario you are using was thought to be useful on a developer machine. But in deployment we would actually discourage using a plain text secrets file, so we wanted to make the UserSecretsConfigBuilder less noisy.

In the end, version 1 of these builders gave some of the builders the `optional` tag. UserSecrets is one of them, and it defaults to `true`. This means you won't get an exception if the secrets file can't be found. The Key Vault config builder was not given the optional tag at that time because the push for Key Vault was to use managed service identities and magical connections through VS or Azure VMs to connect to the correct vaults - the connection would be to different dev/test/stage/deploy vaults depending on the environment. But in your case you don't have that magic set up, so you get the noise.

Version 2 brings the `optional` tag to all the builders. It will default in different directions depending on common usage scenarios, and the key vault builder still defaults to not optional. But you'll be able to override that when you declare the builder. A beta of V2 is available on nuget now. RC will be out in early January when I get nuget access from the folks who were handling the package publishing before me. And RTM (for all but Azure AppConfiguration) will follow that after a short feedback period.

One thing to note (which doesn't seem to affect you, but is a small breaking change from 1->2, so I want to call it out for others reading this): V2 of the key vault builder does not accept connection strings anymore. The `Microsoft.Azure.Services.AppAuthentication` package is not being used to connect to Azure in V2, being replaced with the current `Azure.Identity` and related SDK pacakges instead. These current packages do not allow the direct input of connection strings as an option. See [DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) for details on how this credential works.

**Comment by martingbrown** [comment]
Stephen, thank you for your detailed response.

You mentioned "to use managed service identities and magical connections through VS or Azure VMs to connect to the correct vaults". I don't suppose you know of any guides on how to set that up?

**Comment by StephenMolloy** [comment]
I don't really. That's why I call it magic. If you're in Visual Studio or Azure, it should just work, though I don't know the details of how or why. The only information I have is from the documentation for [DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet).

**Comment by ransagy** [comment]
Adding `optional="true"` doesn't seem to work still; it crashes on processing the KeyVault section, likely due to the connection eror.
